import type { ArenaSettings, GameMode } from './types'

export const ARENA_STORE_VERSION = 1
export const ARENA_STORE_KEY = 'arena-store'
export const ARENA_LOG_MAX = 500

export const DEFAULT_ARENA_SETTINGS: ArenaSettings = {
  themeId: 'enterprise-light',
  themeMode: 'light',
  uiScale: 100,
  animationEnabled: true,
  compactLayout: false,
  glassEffect: true,
  bgmEnabled: true,
  sfxEnabled: true,
  bgmVolume: 60,
  sfxVolume: 70,
  autoSaveMatch: true,
  modelCallHints: true,
  balanceReminder: true,
  balanceReminderThresholdCents: 500,
  dataRetentionDays: 90,
  defaultIdentityAssignMode: 'random',
  matchDefaults: {
    confirmBeforeStart: true,
    pauseOnLowBalance: true,
    autoAdvance: true,
    autoNextRound: true,
    narratorEnabled: true,
    fastMode: false,
    showEmotionTags: true,
  },
}

export const BUILTIN_GAME_MODES: GameMode[] = [
  {
    id: 'werewolf',
    name: '狼人杀',
    subtitle: '经典身份推理',
    description: '狼人阵营与好人阵营在夜晚行动、白天发言和公开投票中交锋。裁判负责身份分配、技能结算、警长流转与胜负判定。',
    minPlayers: 6,
    maxPlayers: 18,
    recommendedPlayers: 10,
    hasHiddenRoles: true,
    hasVoting: true,
    estimatedCostPerPlayerCents: 180,
    estimatedDurationMinutes: 40,
    imageKey: 'werewolf',
    setupSummary: '本局公开使用标准狼人杀流程：警上发言 → 警长投票 → 夜晚行动 → 白天发言 → 放逐投票 → 裁判结算。身份仅对对应 AI 生效，公开频道只展示规则允许的信息。',
    sheriffRule: '首轮进入警长竞选。警长拥有 1.5 票归票权，死亡后裁判会自动移交警徽；若无人可接任则警徽流失。',
    ruleHighlights: [
      '狼人夜晚共同选择一名非狼人目标出局。',
      '预言家每晚查验一名玩家阵营，结果只进入其私有视角。',
      '女巫拥有一次解药和一次毒药，解药救刀口，毒药可额外毒杀一人。',
      '守卫每晚守护一名玩家，不能连续两晚守同一人。守护与狼人刀口相同则免死。',
      '猎人被放逐或夜晚死亡时可开枪带走一人；被毒死时不能开枪。',
      '白痴被投票放逐时翻牌免死，但之后失去投票权。',
      '狼王/白狼王出局时可带走一名玩家；狼美人死亡时魅惑对象殉情；骑士可在放逐投票前决斗一次；守墓人知晓上一夜出局者阵营。',
      '胜负：狼人清零则好人胜；狼人数量不少于存活好人则狼人胜。',
    ],
    roles: [
      {
        id: 'werewolf',
        name: '狼人',
        camp: 'wolf',
        hidden: true,
        description: '狼人阵营成员，夜晚共同刀人，白天隐藏身份并干扰好人推理。',
        skillName: '夜袭',
        skillDescription: '每晚由狼人阵营选择一名非狼人目标。若未被守卫保护或女巫救起，目标在天亮时出局。',
        timing: '夜晚',
        publicInfo: '夜晚只公开死亡结果，不公开狼人身份。',
        nightOrder: 10,
      },
      {
        id: 'villager',
        name: '村民',
        camp: 'good',
        hidden: false,
        description: '无夜晚技能的好人阵营，需要通过发言、票型和逻辑找出狼人。',
        skillName: '公民视角',
        skillDescription: '没有主动技能，拥有白天发言与投票权。',
        timing: '白天',
        publicInfo: '公开身份配置中会说明村民数量，但不会公开具体玩家身份。',
      },
      {
        id: 'seer',
        name: '预言家',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。每晚查验一名玩家属于好人阵营或狼人阵营。',
        skillName: '查验',
        skillDescription: '每晚选择一名玩家，得到其阵营结果。结果只进入预言家私有判断，不直接公开。',
        timing: '夜晚',
        publicInfo: '公开频道只显示预言家已完成行动，不公开查验结果。',
        nightOrder: 20,
      },
      {
        id: 'witch',
        name: '女巫',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。拥有一瓶解药和一瓶毒药，整局各只能使用一次。',
        skillName: '解药 / 毒药',
        skillDescription: '解药可救当晚刀口；毒药可额外毒杀一名玩家。裁判会根据局势自动选择是否使用。',
        timing: '夜晚',
        publicInfo: '公开频道只显示天亮结果，不公开女巫用药细节。',
        nightOrder: 30,
      },
      {
        id: 'guard',
        name: '守卫',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。每晚守护一名玩家，防止其被狼人刀杀。',
        skillName: '守护',
        skillDescription: '每晚选择一名玩家守护，不能连续两晚守护同一目标。守中刀口则目标免死。',
        timing: '夜晚',
        publicInfo: '公开频道不公开守卫目标。',
        nightOrder: 5,
      },
      {
        id: 'hunter',
        name: '猎人',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。死亡时可开枪带走一名玩家，但被女巫毒死时不能开枪。',
        skillName: '开枪',
        skillDescription: '被夜晚击杀或白天放逐时触发，裁判会自动选择最可疑目标。',
        timing: '死亡时',
        publicInfo: '若猎人开枪，会在公开事件中展示枪杀结果。',
      },
      {
        id: 'idiot',
        name: '白痴',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。被投票放逐时可以翻牌免死，但失去后续投票权。',
        skillName: '翻牌免死',
        skillDescription: '首次被白天投票放逐时不出局，公开翻牌，之后保留发言但失去投票权。',
        timing: '放逐时',
        publicInfo: '翻牌会公开展示。',
      },
      {
        id: 'wolf_king',
        name: '狼王',
        camp: 'wolf',
        hidden: true,
        description: '狼人阵营。被放逐或夜晚击杀时可开枪带走一名玩家。',
        skillName: '狼王枪',
        skillDescription: '出局时（不含被毒）可带走一名存活玩家。',
        timing: '死亡时',
        publicInfo: '公开频道只展示带走结果，不公开狼王身份。',
      },
      {
        id: 'white_wolf_king',
        name: '白狼王',
        camp: 'wolf',
        hidden: true,
        description: '狼人阵营。被白天投票放逐时可自爆带走一名玩家。',
        skillName: '自爆',
        skillDescription: '白天投票出局时带走一名存活玩家；夜晚死亡或中毒不触发。',
        timing: '放逐时',
        publicInfo: '公开频道展示自爆带走结果。',
      },
      {
        id: 'wolf_beauty',
        name: '狼美人',
        camp: 'wolf',
        hidden: true,
        description: '狼人阵营。每晚魅惑一名玩家，狼美人死亡时被魅惑者殉情。',
        skillName: '魅惑',
        skillDescription: '每晚魅惑一名非狼人；狼美人出局时被魅惑者一并出局。',
        timing: '夜晚',
        publicInfo: '不公开魅惑目标。',
        nightOrder: 12,
      },
      {
        id: 'knight',
        name: '骑士',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。放逐投票前可决斗一次，目标是狼则狼出局，否则骑士出局。',
        skillName: '决斗',
        skillDescription: '整局一次，在放逐投票结算前对最高票目标发起决斗。',
        timing: '白天',
        publicInfo: '决斗结果会公开。',
      },
      {
        id: 'gravedigger',
        name: '守墓人',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。知晓上一夜出局者的阵营归属（仅自身视角）。',
        skillName: '守墓',
        skillDescription: '每夜记录上一夜出局者属于好人或狼人阵营，结果只进入守墓人判断。',
        timing: '夜晚',
        publicInfo: '不公开守墓人记录。',
        nightOrder: 35,
      },
    ],
    phases: [
      { id: 'sheriff-speech', name: '警上发言', kind: 'discussion', order: 1, description: '所有存活玩家依次发表是否竞选警长及归票思路。' },
      { id: 'sheriff-vote', name: '警长投票', kind: 'vote', order: 2, description: '全体存活玩家投票选出警长，最高票获得警徽。' },
      { id: 'night', name: '夜晚行动', kind: 'night', order: 3, description: '守卫、狼人、预言家、女巫依次行动，裁判结算刀口与技能。' },
      { id: 'day-discuss', name: '白天发言', kind: 'discussion', order: 4, description: '存活玩家按席位发言，警长可引导归票。' },
      { id: 'day-vote', name: '放逐投票', kind: 'vote', order: 5, description: '存活且有投票权的玩家投票，警长票按 1.5 票计入。' },
      { id: 'result', name: '裁判结算', kind: 'result', order: 6, description: '裁判检查胜负、警徽移交与下一轮准备。' },
    ],
  },
  {
    id: 'avalon',
    name: '阿瓦隆',
    subtitle: '阵营策略对抗',
    description: '正义与邪恶围绕任务组队与投票展开博弈。当前版本暂未开放。',
    minPlayers: 5,
    maxPlayers: 10,
    recommendedPlayers: 8,
    hasHiddenRoles: true,
    hasVoting: true,
    estimatedCostPerPlayerCents: 450,
    estimatedDurationMinutes: 35,
    imageKey: 'avalon',
    roles: [
      { id: 'merlin', name: '梅林', camp: 'good', hidden: true },
      { id: 'assassin', name: '刺客', camp: 'evil', hidden: true },
      { id: 'loyal', name: '忠臣', camp: 'good', hidden: false },
      { id: 'minion', name: '爪牙', camp: 'evil', hidden: true },
    ],
    phases: [
      { id: 'team-pick', name: '组队', kind: 'action', order: 1, description: '队长选择任务队员。' },
      { id: 'team-vote', name: '组队投票', kind: 'vote', order: 2, description: '全体投票决定队伍是否通过。' },
      { id: 'mission', name: '任务', kind: 'action', order: 3, description: '队员秘密提交任务结果。' },
    ],
  },
  {
    id: 'undercover',
    name: '谁是卧底',
    subtitle: '语言推理猜测',
    description: '通过描述与投票找出卧底。当前版本暂未开放。',
    minPlayers: 4,
    maxPlayers: 12,
    recommendedPlayers: 6,
    hasHiddenRoles: true,
    hasVoting: true,
    estimatedCostPerPlayerCents: 300,
    estimatedDurationMinutes: 25,
    imageKey: 'undercover',
    roles: [
      { id: 'civilian', name: '平民', camp: 'good', hidden: false },
      { id: 'undercover', name: '卧底', camp: 'evil', hidden: true },
    ],
    phases: [
      { id: 'describe', name: '描述', kind: 'discussion', order: 1, description: '轮流描述自己的词语。' },
      { id: 'vote-out', name: '投票出局', kind: 'vote', order: 2, description: '投票淘汰可疑玩家。' },
    ],
  },
  {
    id: 'custom',
    name: '自定义',
    subtitle: '自由规则创作',
    description: '自定义人数、身份与阶段。当前版本暂未开放。',
    minPlayers: 2,
    maxPlayers: 20,
    recommendedPlayers: 6,
    hasHiddenRoles: true,
    hasVoting: true,
    estimatedCostPerPlayerCents: 400,
    estimatedDurationMinutes: 30,
    imageKey: 'custom',
    roles: [{ id: 'player', name: '玩家', camp: 'neutral', hidden: false }],
    phases: [{ id: 'custom-discuss', name: '讨论', kind: 'discussion', order: 1, description: '自由讨论阶段。' }],
  },
]

export const CHARACTER_MODEL_OPTIONS = [
  { id: 'doubao', label: '豆包' },
  { id: 'gpt-4o', label: 'GPT-4o' },
  { id: 'claude-3-5-sonnet', label: 'Claude 3.5' },
  { id: 'deepseek-chat', label: 'DeepSeek' },
  { id: 'kimi', label: 'Kimi' },
  { id: 'gemini-pro', label: 'Gemini' },
  { id: 'qwen-max', label: '通义千问' },
  { id: 'mistral-large-latest', label: 'Mistral' },
  { id: 'llama-3.1-70b', label: 'Llama' },
  { id: 'hunyuan-turbo', label: '腾讯混元' },
  { id: 'glm-4-plus', label: '智谱 GLM' },
  { id: 'abab6.5-chat', label: 'MiniMax' },
  { id: 'yi-large', label: '零一 Yi' },
  { id: 'ernie-4.0-turbo-8k', label: '文心一言' },
  { id: 'grok-2-1212', label: 'Grok' },
  { id: 'spark-max', label: '讯飞星火' },
]

export const SPEECH_STYLE_OPTIONS = ['温柔', '活泼', '理性', '简洁', '幽默', '高冷', '阴阳怪气', '谨慎']

export const CHARACTER_TAG_PRESETS = [
  '逻辑推理',
  '敏锐观察',
  '冷静沉着',
  '策略思维',
  '团队协作',
  '语言表达',
  '善于伪装',
  '喜欢质疑',
  '擅长总结',
  '情绪共鸣',
]
