import type { ArenaSettings, GameMode } from './types'
import { DEFAULT_ROUNDTABLE_SPEECH_DISPLAY, DEFAULT_WEREWOLF_SPEECH_DISPLAY } from './speech-display'
import { DEFAULT_JUDGE_TTS_VOICE_ID, DEFAULT_TTS_VOICE_ID, MIMO_TTS_MODEL_ID } from './voice-presets'

export { MIMO_TTS_MODEL_ID, DEFAULT_TTS_VOICE_ID, DEFAULT_JUDGE_TTS_VOICE_ID }

export const ARENA_STORE_VERSION = 3
export const ARENA_STORE_KEY = 'arena-store'
export const ARENA_LOG_MAX = 500

/** 裁判、解说等系统角色未单独配置时使用的默认模型 */
export const DEFAULT_ARENA_MODEL_ID = 'mimo-v2.5'
export const DEFAULT_SYSTEM_ROLE_MODEL_ID = DEFAULT_ARENA_MODEL_ID

export const DEFAULT_ARENA_SETTINGS: ArenaSettings = {
  uiScale: 100,
  animationEnabled: true,
  compactLayout: false,
  glassEffect: true,
  bgmEnabled: true,
  sfxEnabled: true,
  bgmVolume: 60,
  sfxVolume: 70,
  ttsEnabled: true,
  ttsVolume: 80,
  judgeVoiceId: DEFAULT_JUDGE_TTS_VOICE_ID,
  autoSaveMatch: true,
  modelCallHints: true,
  balanceReminder: true,
  balanceReminderThresholdCents: 500,
  dataRetentionDays: 90,
  defaultIdentityAssignMode: 'random',
  defaultModelId: DEFAULT_ARENA_MODEL_ID,
  matchDefaults: {
    confirmBeforeStart: true,
    pauseOnLowBalance: true,
    autoAdvance: true,
    autoNextRound: true,
    narratorEnabled: true,
    judgeTtsEnabled: true,
    fastMode: false,
    showEmotionTags: true,
    matchRoomLayout: 'classic',
  },
  characterEvolution: {
    postGameReviewEnabled: true,
    autoApplyBehaviorChanges: true,
  },
}

export const BUILTIN_GAME_MODES: GameMode[] = [
  {
    id: 'werewolf',
    name: '狼人杀',
    subtitle: '经典身份推理',
    description: '狼人阵营与好人阵营在夜晚行动、白天发言和公开投票中交锋。裁判负责身份分配、技能结算、警长流转与胜负判定。',
    minPlayers: 6,
    maxPlayers: 18,
    recommendedPlayers: 10,
    hasHiddenRoles: true,
    hasVoting: true,
    estimatedCostPerPlayerCents: 186,
    estimatedDurationMinutes: 40,
    imageKey: 'werewolf',
    scenarioId: 'werewolf',
    engineKind: 'werewolf',
    speechDisplay: DEFAULT_WEREWOLF_SPEECH_DISPLAY,
    setupSummary: '本局公开使用标准狼人杀流程：警上发言 → 警长投票 → 夜晚行动 → 白天发言 → 放逐投票 → 裁判结算。身份仅对对应 AI 生效，公开频道只展示规则允许的信息。',
    sheriffRule: '首轮进入警长竞选（警上），位于首夜行动之前。此阶段预言家尚未查验，跳预言家只能报身份与警徽流，无法公布验人；勿仅因发言模糊或缺少查验就质疑其为假预言家。警长拥有 1.5 票归票权，死亡后裁判会自动移交警徽；若无人可接任则警徽流失。',
    ruleHighlights: [
      '狼人夜晚共同选择一名非狼人目标出局。',
      '警上发生在首夜行动之前：此阶段预言家尚未查验，警上跳预言家只能谈身份与警徽流，无法也不应公布验人结果；发言偏模糊属正常，勿仅因缺少查验就判定假预言家。',
      '预言家每晚查验一名玩家阵营，结果只进入其私有视角；首夜查验在警长产生后的第一个夜晚进行。',
      '女巫拥有一次解药和一次毒药，解药救刀口，毒药可额外毒杀一人。',
      '守卫每晚守护一名玩家，不能连续两晚守同一人。守护与狼人刀口相同则免死。',
      '标准规则下仅首夜（第一个夜晚）出局者可发表遗言；白天放逐、次夜及以后出局默认无遗言，可在创建对局时勾选规则扩展。',
      '狼人夜晚可袭击好人，亦可在战术需要时自刀或刀队友（骗女巫解药等高级玩法，规则允许）。',
      '猎人被放逐或夜晚死亡时可开枪带走一人；被毒死时不能开枪。',
      '白痴被投票放逐时翻牌免死，但之后失去投票权。',
      '狼王/白狼王出局时可带走一名玩家；狼美人死亡时魅惑对象殉情；骑士可在放逐投票前决斗一次；守墓人知晓上一夜出局者阵营。',
      '胜负：狼人全部出局则好人胜；屠边模式下杀光平民或神职则狼人胜，屠城模式下杀光所有好人则狼人胜（创建对局可选）。',
    ],
    roles: [
      {
        id: 'werewolf',
        name: '狼人',
        camp: 'wolf',
        hidden: true,
        description: '狼人阵营成员，夜晚共同刀人，白天隐藏身份并干扰好人推理。',
        skillName: '夜袭',
        skillDescription: '每晚由狼人阵营选择袭击目标，通常为好人；亦允许自刀或刀队友（骗女巫解药等高级战术）。若未被守卫保护或女巫救起，目标在天亮时出局。',
        timing: '夜晚',
        publicInfo: '夜晚只公开死亡结果，不公开狼人身份。',
        nightOrder: 10,
      },
      {
        id: 'villager',
        name: '村民',
        camp: 'good',
        hidden: false,
        description: '无夜晚技能的好人阵营，需要通过发言、票型和逻辑找出狼人。',
        skillName: '公民视角',
        skillDescription: '没有主动技能，拥有白天发言与投票权。',
        timing: '白天',
        publicInfo: '公开身份配置中会说明村民数量，但不会公开具体玩家身份。',
      },
      {
        id: 'seer',
        name: '预言家',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。每晚查验一名玩家属于好人阵营或狼人阵营。',
        skillName: '查验',
        skillDescription: '每晚选择一名玩家，得到其阵营结果。结果只进入预言家私有判断，不直接公开。首夜查验在警长产生后的第一个夜晚进行，警上阶段尚未查验。',
        timing: '夜晚',
        publicInfo: '公开频道只显示预言家已完成行动，不公开查验结果。',
        nightOrder: 20,
      },
      {
        id: 'witch',
        name: '女巫',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。拥有一瓶解药和一瓶毒药，整局各只能使用一次。',
        skillName: '解药 / 毒药',
        skillDescription: '解药可救当晚刀口；毒药可额外毒杀一名玩家。裁判会根据局势自动选择是否使用。',
        timing: '夜晚',
        publicInfo: '公开频道只显示天亮结果，不公开女巫用药细节。',
        nightOrder: 30,
      },
      {
        id: 'guard',
        name: '守卫',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。每晚守护一名玩家，防止其被狼人刀杀。',
        skillName: '守护',
        skillDescription: '每晚选择一名玩家守护，不能连续两晚守护同一目标。守中刀口则目标免死。',
        timing: '夜晚',
        publicInfo: '公开频道不公开守卫目标。',
        nightOrder: 5,
      },
      {
        id: 'hunter',
        name: '猎人',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。死亡时可开枪带走一名玩家，但被女巫毒死时不能开枪。',
        skillName: '开枪',
        skillDescription: '被夜晚击杀或白天放逐时触发，裁判会自动选择最可疑目标。',
        timing: '死亡时',
        publicInfo: '若猎人开枪，会在公开事件中展示枪杀结果。',
      },
      {
        id: 'idiot',
        name: '白痴',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。被投票放逐时可以翻牌免死，但失去后续投票权。',
        skillName: '翻牌免死',
        skillDescription: '首次被白天投票放逐时不出局，公开翻牌，之后保留发言但失去投票权。',
        timing: '放逐时',
        publicInfo: '翻牌会公开展示。',
      },
      {
        id: 'wolf_king',
        name: '狼王',
        camp: 'wolf',
        hidden: true,
        description: '狼人阵营。被放逐或夜晚击杀时可开枪带走一名玩家。',
        skillName: '狼王枪',
        skillDescription: '出局时（不含被毒）可带走一名存活玩家。',
        timing: '死亡时',
        publicInfo: '公开频道只展示带走结果，不公开狼王身份。',
      },
      {
        id: 'white_wolf_king',
        name: '白狼王',
        camp: 'wolf',
        hidden: true,
        description: '狼人阵营。被白天投票放逐时可自爆带走一名玩家。',
        skillName: '自爆',
        skillDescription: '白天投票出局时带走一名存活玩家；夜晚死亡或中毒不触发。',
        timing: '放逐时',
        publicInfo: '公开频道展示自爆带走结果。',
      },
      {
        id: 'wolf_beauty',
        name: '狼美人',
        camp: 'wolf',
        hidden: true,
        description: '狼人阵营。每晚魅惑一名玩家，狼美人死亡时被魅惑者殉情。',
        skillName: '魅惑',
        skillDescription: '每晚魅惑一名非狼人；狼美人出局时被魅惑者一并出局。',
        timing: '夜晚',
        publicInfo: '不公开魅惑目标。',
        nightOrder: 12,
      },
      {
        id: 'knight',
        name: '骑士',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。放逐投票前可决斗一次，目标是狼则狼出局，否则骑士出局。',
        skillName: '决斗',
        skillDescription: '整局一次，在放逐投票结算前对最高票目标发起决斗。',
        timing: '白天',
        publicInfo: '决斗结果会公开。',
      },
      {
        id: 'gravedigger',
        name: '守墓人',
        camp: 'good',
        hidden: false,
        isGod: true,
        description: '神职。知晓上一夜出局者的阵营归属（仅自身视角）。',
        skillName: '守墓',
        skillDescription: '每夜记录上一夜出局者属于好人或狼人阵营，结果只进入守墓人判断。',
        timing: '夜晚',
        publicInfo: '不公开守墓人记录。',
        nightOrder: 35,
      },
    ],
    phases: [
      { id: 'sheriff-speech', name: '警上发言', kind: 'discussion', order: 1, description: '首夜行动前的警长竞选发言。预言家此阶段尚未查验，跳预言家者只能说明身份与警徽流，无法公布验人；勿因缺少查验信息而判定假预言家。' },
      { id: 'sheriff-vote', name: '警长投票', kind: 'vote', order: 2, description: '全体存活玩家从警上竞选者中投票选出警长，最高票获得警徽。' },
      { id: 'night', name: '夜晚行动', kind: 'night', order: 3, description: '守卫、狼人、预言家、女巫依次行动，裁判结算刀口与技能。' },
      { id: 'day-discuss', name: '白天发言', kind: 'discussion', order: 4, description: '存活玩家按席位发言，警长可引导归票。' },
      { id: 'day-vote', name: '放逐投票', kind: 'vote', order: 5, description: '存活且有投票权的玩家投票，警长票按 1.5 票计入。标准规则下被放逐者无遗言。' },
      { id: 'result', name: '裁判结算', kind: 'result', order: 6, description: '裁判检查胜负、警徽移交与下一轮准备。' },
    ],
  },
  {
    id: 'avalon',
    name: '阿瓦隆',
    subtitle: '阵营策略对抗',
    description: '正义与邪恶围绕任务组队与投票展开博弈。当前版本暂未开放。',
    minPlayers: 5,
    maxPlayers: 10,
    recommendedPlayers: 8,
    hasHiddenRoles: true,
    hasVoting: true,
    estimatedCostPerPlayerCents: 450,
    estimatedDurationMinutes: 35,
    imageKey: 'avalon',
    roles: [
      { id: 'merlin', name: '梅林', camp: 'good', hidden: true },
      { id: 'assassin', name: '刺客', camp: 'evil', hidden: true },
      { id: 'loyal', name: '忠臣', camp: 'good', hidden: false },
      { id: 'minion', name: '爪牙', camp: 'evil', hidden: true },
    ],
    phases: [
      { id: 'team-pick', name: '组队', kind: 'action', order: 1, description: '队长选择任务队员。' },
      { id: 'team-vote', name: '组队投票', kind: 'vote', order: 2, description: '全体投票决定队伍是否通过。' },
      { id: 'mission', name: '任务', kind: 'action', order: 3, description: '队员秘密提交任务结果。' },
    ],
  },
  {
    id: 'undercover',
    name: '谁是卧底',
    subtitle: '语言推理猜测',
    description: '通过描述与投票找出卧底。',
    minPlayers: 4,
    maxPlayers: 12,
    recommendedPlayers: 6,
    hasHiddenRoles: true,
    hasVoting: true,
    estimatedCostPerPlayerCents: 300,
    estimatedDurationMinutes: 25,
    imageKey: 'undercover',
    scenarioId: 'undercover',
    engineKind: 'undercover',
    setupSummary: '轮流描述词语、投票出局卧底。平民与卧底各持一词，通过描述与投票博弈。',
    ruleHighlights: [
      '每人持有一个词语，卧底词与平民词相近。',
      '轮流描述，不可直接说出词语。',
      '投票淘汰可疑玩家，找出所有卧底则平民胜。',
    ],
    roles: [
      { id: 'civilian', name: '平民', camp: 'good', hidden: false, description: '持有平民词，找出卧底。' },
      { id: 'undercover', name: '卧底', camp: 'evil', hidden: true, description: '持有卧底词，隐藏身份。' },
    ],
    phases: [
      { id: 'describe', name: '描述', kind: 'discussion', order: 1, description: '轮流描述自己的词语。' },
      { id: 'vote-out', name: '投票出局', kind: 'vote', order: 2, description: '投票淘汰可疑玩家。' },
    ],
  },
  {
    id: 'roundtable',
    name: '圆桌讨论',
    subtitle: '议题讨论',
    description: '围绕议题进行多轮发言，倾听与回应，无胜负与产物。',
    minPlayers: 2,
    maxPlayers: 12,
    recommendedPlayers: 4,
    hasHiddenRoles: false,
    hasVoting: false,
    estimatedCostPerPlayerCents: 112,
    estimatedDurationMinutes: 20,
    imageKey: 'roundtable',
    scenarioId: 'roundtable',
    engineKind: 'roundtable',
    speechDisplay: DEFAULT_ROUNDTABLE_SPEECH_DISPLAY,
    setupSummary: '多轮圆桌发言，玩家担任裁判在轮间总结引导或解说；结束时产出讨论纪要。',
    ruleHighlights: [
      '开局前设定议题、发言轮数与裁判引导方式。',
      '不支持 AI 解说与用户分身参战，由你担任裁判。',
      '每轮全员发言后由你总结引导或解说，再进入下一轮。',
      '结束时归纳讨论产物（共识、分歧、开放问题等）。',
    ],
    roles: [{ id: 'participant', name: '参与者', camp: 'neutral', hidden: false, description: '圆桌讨论参与者。' }],
    phases: [
      { id: 'opening', name: '开场', kind: 'action', order: 1, description: '裁判介绍议题与流程。' },
      { id: 'round-discuss', name: '圆桌发言', kind: 'discussion', order: 2, description: '按席位轮流发言；每轮结束后由裁判引导下一轮。' },
      { id: 'closing', name: '产物归纳', kind: 'result', order: 3, description: '归纳讨论纪要产物。' },
    ],
  },
  {
    id: 'brainstorm-game-design',
    name: '头脑风暴 · 玩法设计',
    subtitle: '讨论 + 规则产物',
    description: '发散讨论局内流程、开局配置与规则漏洞，产出可落地的玩法草案。',
    minPlayers: 2,
    maxPlayers: 10,
    recommendedPlayers: 4,
    hasHiddenRoles: false,
    hasVoting: false,
    estimatedCostPerPlayerCents: 140,
    estimatedDurationMinutes: 25,
    imageKey: 'custom',
    scenarioId: 'brainstorm-game-design',
    engineKind: 'brainstorm',
    speechDisplay: DEFAULT_ROUNDTABLE_SPEECH_DISPLAY,
    setupSummary: '发散讨论玩法流程与开局配置；玩家担任裁判引导轮次，最后归纳玩法产物。',
    ruleHighlights: [
      '聚焦可执行的规则与阶段设计。',
      '玩家担任裁判，每轮后总结引导或解说。',
      '不支持用户 AI 分身参战。',
      '结束时输出结构化玩法草案。',
    ],
    roles: [{ id: 'participant', name: '参与者', camp: 'neutral', hidden: false, description: '头脑风暴参与者。' }],
    phases: [
      { id: 'opening', name: '开场', kind: 'action', order: 1, description: '明确议题与设计焦点。' },
      { id: 'round-discuss', name: '发散讨论', kind: 'discussion', order: 2, description: '多轮发言，提出与补充想法。' },
      { id: 'closing', name: '产物归纳', kind: 'result', order: 3, description: '归纳玩法产物与待办清单。' },
    ],
  },
  {
    id: 'brainstorm-character-design',
    name: '头脑风暴 · 角色塑造',
    subtitle: '讨论 + 人设产物',
    description: '讨论人设、口吻与行为原则，产出可写入提示词的角色塑造草案。',
    minPlayers: 2,
    maxPlayers: 10,
    recommendedPlayers: 4,
    hasHiddenRoles: false,
    hasVoting: false,
    estimatedCostPerPlayerCents: 140,
    estimatedDurationMinutes: 25,
    imageKey: 'custom',
    scenarioId: 'brainstorm-character-design',
    engineKind: 'brainstorm',
    speechDisplay: DEFAULT_ROUNDTABLE_SPEECH_DISPLAY,
    setupSummary: '围绕角色塑造发散讨论；玩家担任裁判引导轮次，最后归纳人设产物。',
    ruleHighlights: [
      '从可识别行为出发，而非空泛形容词。',
      '玩家担任裁判，每轮后总结引导或解说。',
      '不支持用户 AI 分身参战。',
      '结束时输出结构化角色塑造清单。',
    ],
    roles: [{ id: 'participant', name: '参与者', camp: 'neutral', hidden: false, description: '头脑风暴参与者。' }],
    phases: [
      { id: 'opening', name: '开场', kind: 'action', order: 1, description: '明确塑造目标与设计焦点。' },
      { id: 'round-discuss', name: '发散讨论', kind: 'discussion', order: 2, description: '多轮发言，提出与补充想法。' },
      { id: 'closing', name: '产物归纳', kind: 'result', order: 3, description: '归纳角色塑造产物。' },
    ],
  },
  {
    id: 'custom',
    name: '自定义',
    subtitle: '自由规则创作',
    description: '完全自定义规则与提示词。当前版本暂未开放。',
    minPlayers: 2,
    maxPlayers: 20,
    recommendedPlayers: 6,
    hasHiddenRoles: true,
    hasVoting: true,
    estimatedCostPerPlayerCents: 400,
    estimatedDurationMinutes: 30,
    imageKey: 'custom',
    engineKind: 'prompt-only',
    roles: [{ id: 'player', name: '玩家', camp: 'neutral', hidden: false }],
    phases: [{ id: 'custom-discuss', name: '讨论', kind: 'discussion', order: 1, description: '自由讨论阶段。' }],
  },
]

export const CHARACTER_MODEL_OPTIONS = [
  { id: 'mimo-v2.5', label: 'MiMo v2.5' },
  { id: 'mimo-v2.5-pro', label: 'MiMo v2.5 Pro' },
  { id: 'doubao', label: '豆包' },
  { id: 'gpt-4o', label: 'GPT-4o' },
  { id: 'claude-3-5-sonnet', label: 'Claude 3.5' },
  { id: 'deepseek-chat', label: 'DeepSeek' },
  { id: 'kimi', label: 'Kimi' },
  { id: 'gemini-pro', label: 'Gemini' },
  { id: 'qwen-max', label: '通义千问' },
  { id: 'mistral-large-latest', label: 'Mistral' },
  { id: 'llama-3.1-70b', label: 'Llama' },
  { id: 'hunyuan-turbo', label: '腾讯混元' },
  { id: 'glm-4-plus', label: '智谱 GLM' },
  { id: 'abab6.5-chat', label: 'MiniMax' },
  { id: 'yi-large', label: '零一 Yi' },
  { id: 'ernie-4.0-turbo-8k', label: '文心一言' },
  { id: 'grok-2-1212', label: 'Grok' },
  { id: 'spark-max', label: '讯飞星火' },
]

export const SPEECH_STYLE_OPTIONS = ['温柔', '活泼', '理性', '简洁', '幽默', '高冷', '阴阳怪气', '谨慎']

export const CHARACTER_TAG_PRESETS = [
  '逻辑推理',
  '敏锐观察',
  '冷静沉着',
  '策略思维',
  '团队协作',
  '语言表达',
  '善于伪装',
  '喜欢质疑',
  '擅长总结',
  '情绪共鸣',
]
